AWSTemplateFormatVersion: 2010-09-09
Description: CI/CD pipeline for portal project
Parameters:
  GitHubOwner:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]+"
    Default: cloudhesive
  GitHubRepository:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]+"
    Default: consorcio-seguros
  GitHubBranch:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]+"
    Default: develop
  CodeBuildEnvironmentImage:
    Type: String
    Default: "aws/codebuild/standard:5.0"
  Stage:
    Type: String
  BucketKey:
    Type: String
  horario:
    Type: String
    Default: "lu-vi 800-1900"

Resources:
  CodeBuildServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: CSCodeBuildPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              #- Sid: FullControlPolicy
              #  Effect: Allow
              #  Action:
              #    - "*"
              #  Resource:
              #    - "*"
              - Sid: CloudWatchLogsPolicy
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DeleteLogGroup"
                Resource:
                  - "*"
              - Sid: S3ObjectsPolicy
                Effect: Allow
                Action:
                  #- "s3:GetObject"
                  #- "s3:GetObjectVersion"
                  #- "s3:PutObject"
                  #- "s3:GetBucketAcl"
                  #- "s3:GetBucketLocation"
                  - "s3:*"
                Resource:
                  - "*"
              - Sid: SESPolicy
                Effect: Allow
                Action:
                  - "ses:GetIdentityVerificationAttributes"
                  - "ses:GetEmailIdentity"
                Resource:
                  - "*"
              - Sid: CloudFormationPolicy
                Effect: Allow
                Action:
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:GetTemplateSummary"
                  - "cloudformation:ListExports"
                  - "cloudformation:CreateChangeSet"
                  - "cloudformation:ValidateTemplate"
                  - "cloudformation:CreateStack"
                  - "cloudformation:DescribeStackEvents"
                  - "cloudformation:UpdateStack"
                  - "cloudformation:ListStackResources"
                Resource:
                  - "*"
              - Sid: CodeBuildPolicy
                Effect: Allow
                Action:
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:BatchGetBuilds"
                Resource:
                  - "*"
              - Sid: LambdasInvokesPolicy
                Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                  - "lambda:GetFunction"
                  - "lambda:UpdateFunctionCode"
                  - "lambda:DeleteFunction"
                  - "lambda:CreateFunction"
                  - "lambda:AddPermission"
                  - "lambda:RemovePermission"
                  - "lambda:UpdateFunctionConfiguration"
                  - "lambda:GetEventSourceMapping"
                  - "lambda:CreateEventSourceMapping"
                  - "lambda:DeleteEventSourceMapping"
                Resource:
                  - "*"
              - Sid: ApiGatewayPolicy
                Effect: Allow
                Action:
                  - "apigateway:POST"
                  - "apigateway:GET"
                  - "apigateway:PUT"
                  - "apigateway:DELETE"
                Resource:
                  - "*"
              - Sid: IamPolicy
                Effect: Allow
                Action:
                  - "iam:GetRole"
                  - "iam:CreateRole"
                  - "iam:PutRolePolicy"
                  - "iam:AttachRolePolicy"
                  - "iam:PassRole"
                  - "iam:DeleteRolePolicy"
                  - "iam:DetachRolePolicy"
                  - "iam:DeleteRole"
                  - "iam:getRolePolicy"
                Resource:
                  - "*"
              - Sid: ConfigPolicy
                Effect: Allow
                Action:
                  - "config:PutDeliveryChannel"
                  - "config:DescribeConfigurationRecorders"
                  - "config:DescribeDeliveryChannels"
                  - "config:PutConfigurationRecorder"
                  - "config:StartConfigurationRecorder"
                  - "config:StopConfigurationRecorder"
                  - "config:DeleteConfigurationRecorder"
                Resource:
                  - "*"
              - Sid: EC2Policy
                Effect: Allow
                Action:
                  - "ec2:DescribeKeyPairs"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeVpcs"
                  - "ec2:DescribeRouteTables"
                  - "ec2:DescribeNatGateways"
                Resource:
                  - "*"
              - Sid: SSMPolicy
                Effect: Allow
                Action:
                  - "ssm:GetParameters"
                Resource:
                  - "*"
              - Sid: CloudFrontPolicy
                Effect: Allow
                Action:
                  - "cloudfront:CreateInvalidation"
                Resource:
                  - "*"
              - Sid: EventsPolicy
                Effect: Allow
                Action:
                  - "events:DescribeRule"
                  - "events:PutRule"
                  - "events:PutTargets"
                  - "events:RemoveTargets"
                  - "events:DeleteRule"
                  - "events:TagResource"
                  - "events:CreateEventBus"
                  - "events:PutPermission"
                  - "events:DeleteEventBus"
                  - "events:DescribeEventBus"
                  - "events:ListRules"
                Resource:
                  - "*"
              - Sid: StepFunctionsPolicy
                Effect: Allow
                Action:
                  - "*"
                Resource:
                  - "*"
              - Sid: SqsPolicy
                Effect: Allow
                Action:
                  - "sqs:*"
                Resource:
                  - "*"
      Tags:
        - Key: CC
          Value: 9301
        - Key: Proyecto
          Value: Dev Portal
        - Key: ambiente
          Value: ci-cd
        - Key: idAplicativo
          Value: Dev Portal
        - Key: responsable
          Value: ingenieria
        - Key: horarioEncendido
          Value: !Ref horario
        - Key: backup
          Value: bronze

  CodePipelineArtifactStore:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref BucketKey
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: CC
          Value: 9301
        - Key: Proyecto
          Value: Dev Portal
        - Key: ambiente
          Value: ci-cd
        - Key: idAplicativo
          Value: Dev Portal
        - Key: responsable
          Value: ingenieria

  CodePipelineWebhook:
    Type: "AWS::CodePipeline::Webhook"
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: "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"
      RegisterWithThirdParty: "true"
      Filters:
        - JsonPath: $.ref
          MatchEquals: "refs/heads/{Branch}"
        - JsonPath: $.repository.name
          MatchEquals: "{Repo}"
      TargetPipeline: !Ref CodePipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt
        - CodePipeline
        - Version

  CodeBuilProjectDeploy:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: !Sub "${AWS::StackName}-deploy-${AWS::Region}"
      ServiceRole: !GetAtt
        - CodeBuildServiceRole
        - Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: !Ref CodeBuildEnvironmentImage
      Tags:
        - Key: CC
          Value: 9301
        - Key: Proyecto
          Value: Dev Portal
        - Key: ambiente
          Value: ci-cd
        - Key: idAplicativo
          Value: Dev Portal
        - Key: responsable
          Value: ingenieria

  CodePipelineServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: CSPipelinePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CloudWatchLogsPolicy
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - "*"
              - Sid: S3GetObjectPolicy
                Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                Resource:
                  - "*"
              - Sid: S3PutObjectPolicy
                Effect: Allow
                Action:
                  - "s3:PutObject"
                Resource:
                  - "*"
              - Sid: S3BucketIdentity
                Effect: Allow
                Action:
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"
                Resource:
                  - "*"
              - Sid: CodeBuildPolicy
                Action:
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:StartBuild"
                Resource: "*"
                Effect: Allow
      Tags:
        - Key: CC
          Value: 9301
        - Key: Proyecto
          Value: Dev Portal
        - Key: ambiente
          Value: ci-cd
        - Key: idAplicativo
          Value: Dev Portal
        - Key: responsable
          Value: ingenieria

  CodePipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Ref "AWS::StackName"
      RoleArn: !GetAtt
        - CodePipelineServiceRole
        - Arn
      ArtifactStore:
        Type: S3
        Location: !Ref CodePipelineArtifactStore
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepository
                Branch: !Ref GitHubBranch
                PollForSourceChanges: false
                OAuthToken: "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"
                #OAuthToken: >-
                #  {{resolve:secretsmanager:GITHUB_ACCESS:SecretString:GITHUB_ACCESS_TOKEN}} #TODO
              OutputArtifacts:
                - Name: SourceCode
        - Name: !Ref Stage
          Actions:
            - Name: Approval
              RunOrder: 1
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: "1"
              Configuration:
                CustomData: Approve or Reject this change
            - Name: Deploy
              RunOrder: 2
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuilProjectDeploy
                EnvironmentVariables: !Sub '[{"name":"CURRENT_ENVIRONMENT","value":"${Stage}","type":"PLAINTEXT"}]'
              InputArtifacts:
                - Name: SourceCode
      Tags:
        - Key: CC
          Value: 9301
        - Key: Proyecto
          Value: Dev Portal
        - Key: ambiente
          Value: ci-cd
        - Key: idAplicativo
          Value: Dev Portal
        - Key: responsable
          Value: ingenieria
