Resources:
  DeploymentNotificationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${env:STAGE}-deployment-notification-queue
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - 'DeploymentNotificationDeadLetterQueue'
            - 'Arn'
        maxReceiveCount: 5
      Tags:
        - Key: CC
          Value: 9301
        - Key: Proyecto
          Value: Dev Portal
        - Key: ambiente
          Value: ci-cd
        - Key: idAplicativo
          Value: Dev Portal
        - Key: responsable
          Value: ingenieria
  DeploymentNotificationDeadLetterQueue:
    Type: 'AWS::SQS::Queue'
